main/urls.py
from django.urls import path
from . import views

app_name="main"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path("<single_slug>", views.single_slug, name="single_slug"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('main.urls')),
    
]

main/models.py
from django.db import models


class TutorialCategory(models.Model):
    tutorial_category = models.CharField(max_length=200)
    category_summary = models.CharField(max_length=200)
    category_slug = models.CharField(max_length=200, default=1)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.tutorial_category


class TutorialSeries(models.Model):
    tutorial_series = models.CharField(max_length=200)
    tutorial_category = models.ForeignKey(TutorialCategory, verbose_name= "Category", on_delete=models.SET_DEFAULT, default=1)
    series_summary = models.CharField(max_length=200)
    
    class Meta:
        verbose_name_plural = "Series"

    def __str__(self):
        return self.tutorial_series



# Create your models here.
class Tutorial(models.Model):
    tutorial_title = models.CharField(max_length=200)
    tutorial_content = models.TextField()
    tutorial_published = models.DateTimeField("date published")

    tutorial_series = models.ForeignKey(TutorialSeries, verbose_name= "Series", on_delete=models.SET_DEFAULT, default=1)
    tutorial_slug = models.CharField(max_length=200, default=1)
    
    def __str__(self):
        return self.tutorial_title

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    email =  forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Tutorial, TutorialCategory, TutorialSeries
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import NewUserForm


def single_slug(request, single_slug):
    categories = [c.category_slug for c in TutorialCategory.objects.all()]
    if single_slug in categories:
        matching_series = TutorialSeries.objects.filter(tutorial_category__category_slug=single_slug)

        series_urls = {}
        for m in matching_series.all():
            part_one = Tutorial.objects.filter(tutorial_series__tutorial_series=m.tutorial_series).earliest("tutorial_published")
            series_urls[m] = part_one.tutorial_slug


        return render(request, 
                        "main/category.html",
                        {"part_ones": series_urls})

    tutorials = [t.tutorial_slug for t in Tutorial.objects.all()]
    if single_slug in tutorials:
        this_tutorial = Tutorial.objects.get(tutorial_slug = single_slug)
        tutorials_from_series = Tutorial.objects.filter(tutorial_series__tutorial_series=this_tutorial.tutorial_series).order_by("tutorial_published")

        this_tutorial_idx = list(tutorials_from_series).index(this_tutorial)

        return render(request,
                        "main/tutorial.html",
                        {"tutorial":this_tutorial,
                         "sidebar": tutorials_from_series,
                         "this_tutorial_idx": this_tutorial_idx})

    return HttpResponse(f"{single_slug} does not correspond to anything.")



def homepage(request):
    return render(request=request, 
                    template_name="main/categories.html",
                    context={"categories": TutorialCategory.objects.all})
# Create your views here.

def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"New Account Created: {username}" )
            login(request, user)
            messages.info(request, f"You are now logged in as {username}" )
            return redirect("main:homepage")
        else: 
            for msg in form.error_messages:
                messages.error(request, f"{msg}:{form.error_messages[msg]}")
                




    form = NewUserForm
    return render(request,
                    "main/register.html",
                    context={"form": form})


def logout_request(request): 
    logout(request)
    messages.info(request, "Logged out Successfully!")
    return redirect("main:homepage")

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username') 
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}" )
                return redirect("main:homepage")
            else: 
                messages.error(request, "Invalid Username or Password")   
    else: 
        messages.error(request, "Invalid Username or Password")   

    form = AuthenticationForm()
    return render(request,
                    "main/login.html",
                    {"form": form})

main/templates/main/categories.html
{% extends 'main/header.html' %}

{% block content %}

    <div class="row">
        {% for cat in categories %}
            <div class="col s12 m6 l4">
                <a href="{{cat.category_slug}}", style="color:#000">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title">{{cat.tutorial_category}}</div>
                            <p>{{cat.category_summary}}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

main/templates/main/category.html
{% extends 'main/header.html' %}

{% block content %}

    <div class="row">
        {% for tut, partone in part_ones.items %}

            <div class="col s12 m6 l4">
                <a href="{{partone}}", style="color:#000">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title">{{tut.tutorial_series}}</div>
                            <p>{{tut.series_summary}}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

main/templates/main/header.html
<head>
    {% load static %}
    <link href = "{% static 'tinymce/css/prism.css' %}" rel= "stylesheet">
    <!-- Compiled and minified CSS -->
    <link href = "{% static 'main/css/materialize.css' %}" rel= "stylesheet">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
</head>


<body>

  {% include "main/includes/navbar.html" %}

  {% include "main/includes/messages.html" %}

  <div class="container"> 
    <br>    
    {% block content %}
    {% endblock %}
  </div>

</body>

<script src="{% static 'tinymce/js/prism.js' %}"> </script>

<script>M.AutoInit();</script>

main/templates/main/home.html
{% extends "main/header.html" %}

{% block content %}
    <div class="row">
        {% for tut in tutorials %}
        <div class="col s12 m6 l4">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title">{{ tut.tutorial_title }}</span>
                    <p style="font-size:70%">{{ tut.tutorial_published }}</p>
                    <p>{{ tut.tutorial_content|safe}}</p>
                </div>
                <div class="card-action">
                    <a href="#">Visit</a>
                </div>
                
            </div>
        </div>
        {% endfor %}
    </div> 
{% endblock %}

main/templates/main/includes/messages.html
  {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
            {% elif message.tags == 'info'%}
                <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
            {% elif message.tags == 'warning'%}
                <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
            {% elif message.tags == 'error'%}
                <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
            {% endif %}
        {% endfor %}
    {% endif %}
        

main/templates/main/includes/navbar.html
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Tutorials!</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        {% if user.is_authenticated %}
          <li><a href="/account">{{ user.username }}</a></li>
          <li><a href="{% url 'main:logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'main:register' %}">Register</a></li>
          <li><a href="{% url 'main:login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

main/templates/main/login.html
{% extends "main/header.html" %}


{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <br>
        <button class="btn" style="background-color:default; color:default" type="submit"> Login </button>
    </form>

    If you don't have an account, <a href ="/register"><strong>register</strong></a> for one.
{% endblock %}

main/templates/main/register.html
{% extends "main/header.html" %}


{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <br>
        <button class="btn" style="background-color:default; color:default" type="submit"> Register </button>
    </form>

    If you already have an account, <a href ="/login"><strong>login</strong></a> instead.
{% endblock %}

main/templates/main/tutorial.html
{% extends 'main/header.html' %}

{% block content %}

    <div class="row">

        <div class="col s12, m8, l8">
            <h3>{{tutorial.tutorial_title}}</h3>
            <p style="font-size:70%">Published {{tutorial.tutorial_published}}</p>
            {{tutorial.tutorial_content|safe}}
        </div>

        <div class="col s12 m4 l4">
            <ul class="collapsible popout">
                {% for tutorial in sidebar %}
                    {% if forloop.counter0 == this_tutorial_idx %}
                        <li class="active">
                            <div class="collapsible-header">{{tutorial.tutorial_title}}<br>(currently viewing)</div>
                        </li>
                    {% else %}
                        <li>
                            <div class="collapsible-header">{{tutorial.tutorial_title}}</div>
                            <div class="collapsible-body">
                                <p><a href="/{{tutorial.tutorial_slug}}"><button class="btn waves-effect waves-light right-align" style="background-color:yellow; color:black">Go</button></a></p>

                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>

    </div>

{% endblock %}